openapi: 3.1.0
info:
  title: PEAC Protocol API
  version: 0.9.6
  description: Programmable Environment for Agent Coordination
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: https://api.peacprotocol.org
    description: Production server
  - url: http://localhost:3000
    description: Development server

security: []

paths:
  /.well-known/peac-capabilities:
    get:
      summary: Get PEAC capabilities
      operationId: getCapabilities
      tags:
        - Discovery
      parameters:
        - name: Accept
          in: header
          required: false
          schema:
            type: string
            default: application/vnd.peac.capabilities+json;version=0.9.6
      responses:
        "200":
          description: Capabilities retrieved successfully
          content:
            application/vnd.peac.capabilities+json;version=0.9.6:
              schema:
                $ref: "#/components/schemas/Capabilities"
            application/json:
              schema:
                $ref: "#/components/schemas/Capabilities"
        "406":
          description: Not Acceptable
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"

components:
  schemas:
    Capabilities:
      type: object
      required:
        - version
        - conformance_level
        - protocols
        - payments
        - features
      properties:
        version:
          type: string
          example: "0.9.6"
        conformance_level:
          type: string
          enum: [L0, L1, L2, L3, L4]
        protocols:
          type: object
          properties:
            bridges:
              type: array
              items:
                type: string
              example: ["mcp", "a2a", "openai", "langchain"]
            native_a2a:
              type: object
              properties:
                handshake:
                  type: boolean
                orchestration:
                  type: array
                  items:
                    type: string
        payments:
          type: object
          properties:
            rails:
              type: array
              items:
                type: string
            status:
              type: object
              additionalProperties:
                type: string
            message:
              type: string
        features:
          type: object
        discovery:
          type: object
          properties:
            rank_explanations:
              type: boolean
        limits:
          type: object
        links:
          type: object

    ProblemDetails:
      type: object
      required:
        - title
        - status
      properties:
        type:
          type: string
          format: uri
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
          format: uri