packages:
  - 'packages/*'
  - 'packages/rails/*'
  - 'packages/mappings/*'
  - 'packages/transport/*'
  - 'apps/*'
  - 'surfaces/analytics'
  - 'surfaces/workers/*'
  - 'surfaces/nextjs/*'
  - 'examples/*'
