packages:
  - 'packages/*'
  - 'packages/*/*'
  - 'packages/*/*/*'
  - 'packages/adapters/*'
  - 'apps/*'
  - 'schemas'
  - 'profiles'
  - 'examples'
  - 'docs'
  - 'tests'
  - 'tooling'
  - 'infra'
  - 'tools/*'
  - '!archive/**'
