
name: CI/CD for PEAC
on: [push, pull_request]
jobs:
  test-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: { node-version: 18 }
      - run: npm install
      - run: npm test
  test-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: { python-version: 3.12 }
      - run: pip install -r requirements.txt
      - run: pytest
