# golangci-lint configuration for PEAC Go SDK
# Compatible with golangci-lint v1.x

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple

linters-settings:
  errcheck:
    exclude-functions:
      - (*testing.T).Errorf
      - (*testing.T).Fatalf
      - (*testing.T).Error
      - (*testing.T).Fatal

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
