# golangci-lint configuration for PEAC Go SDK
# Compatible with golangci-lint v2.x

version: '2'

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple
